GET http://localhost:8080/users
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
  "name": "Vasil",
  "age": 25
}
###

GET http://localhost:8080/users/2
Accept: application/json
Content-Type: application/json

###

