
### get all users
GET https://golang-crud-obcf.onrender.com/users
Accept: application/json
Content-Type: application/json

### create one user
POST https://golang-crud-obcf.onrender.com/users
Accept: application/json
Content-Type: application/json

{
  "name": "Иосиф Сталин",
  "age": 68
}
### Get one user by id
GET https://golang-crud-obcf.onrender.com/users/1
Accept: application/json
Content-Type: application/json

### Update user by ids
PUT https://golang-crud-obcf.onrender.com/users/2
Accept: application/json
Content-Type: application/json

{
  "name": "Caban",
  "age": 35
}

### delete user by id
DELETE https://golang-crud-obcf.onrender.com/users/1
Accept: application/json
Content-Type: application/json


